language: bash

os:
- linux
- osx

jdk:
- openjdk8

branches:
  only:
  - master

jobs:
  allow_failures:
  - os: osx

install:
- mkdir ./programs ; cd ./programs ; export PATH=$PATH:$PWD
- curl -fsSL https://get.nextflow.io | bash
- cd ..
- if [ "$TRAVIS_OS_NAME" = "linux" ]; then wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh
  -O miniconda.sh; fi
- if [ "$TRAVIS_OS_NAME" = "osx" ];   then curl https://repo.anaconda.com/miniconda/Miniconda3-latest-MacOSX-x86_64.sh
  -o miniconda.sh; fi
- bash miniconda.sh -b -p $HOME/miniconda
- source "$HOME/miniconda/etc/profile.d/conda.sh"
- hash -r
- conda config --set always_yes yes --set changeps1 no
- conda update -q conda
- conda info -a

script:
- if [ "$TRAVIS_OS_NAME" = "linux" ]; then set -e ; fi
- export NXF_ANSI_LOG=false
- mkdir ./test_init
- cd    ./test_init
- nextflow run ../CnR-flow.nf --mode initiate
- nextflow run ../CnR-flow.nf --mode validate_all
- cd ../test_pipe
- cat test_notes.txt
- ./setup_reference.sh
- ./dl_prep_data.sh
- nextflow ../CnR-flow.nf --verbose --mode prep_fasta
- nextflow ../CnR-flow.nf --verbose --mode run
- cp nextflow.config.step2 nextflow.config
- nextflow ../CnR-flow.nf -resume --verbose --mode run

