version: 2.1
jobs:
  test-bash:
    docker:
      - image: continuumio/miniconda3
    steps:
      - checkout
      - run: mkdir ./programs ; cd ./programs ; export PATH=$PATH:$PWD ; echo "Path Set"
      - run: curl -fsSL https://get.nextflow.io | bash
      - run: cd ..
      - run: nextflow
      - run: docker

workflows:
  test-all:
      jobs:
        - test-bash
