version: 2.1
jobs:
  test-bash:
    machine:
      image: ubuntu-2004:202111-02
    steps:
      - checkout
      - run: 
          name: Setup Directories
          command: |
            pwd
            mkdir ./programs
            cd ./programs
            echo 'export PATH=$PATH:$PWD' >> $BASH_ENV
      - run: pwd; echo $PATH
      - run:
          name: Download Nextflow
          command: |
            pwd
            cd ./programs
            curl -fsSL https://get.nextflow.io | bash
      - run:
          name: Download & Install Conda
          command: |
            pwd
            cd ./programs
            wget --progress=dot --retry-connrefused https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
            bash miniconda.sh -b -p $HOME/miniconda
            source "$HOME/miniconda/etc/profile.d/conda.sh"
            hash -r
            conda config --set always_yes yes --set changeps1 no
            conda update -q conda
            conda info -a
      - run: pwd; conda
      - run: pwd; nextflow
      - run: pwd; docker

workflows:
  test-all:
      jobs:
        - test-bash
