version: 2.1
jobs:
  test-bash:
    machine:
      image: ubuntu-2004:202111-02
    steps:
      - checkout
      - run: mkdir ./programs ; cd ./programs ; export PATH=$PATH:$PWD
      - run: curl -fsSL https://get.nextflow.io | bash
      - run: wget --progress=dot --retry-connrefused https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
      - run: bash miniconda.sh -b -p $HOME/miniconda
      - run: source "$HOME/miniconda/etc/profile.d/conda.sh"
      - run: hash -r
      - run: ls
      - run: ls $HOME
      - run: conda config --set always_yes yes --set changeps1 no
      - run: conda update -q conda
      - run: conda info -a
      - run: ls ; cd .. ; ls
      - run: conda
      - run: nextflow
      - run: docker

workflows:
  test-all:
      jobs:
        - test-bash
