version: 2.1
jobs:
  test-bash:
    docker:
      - image: quay.io/biocontainers/nextflow:21.10.6--h4a94de4_0
    steps:
      - checkout
      - run: conda
      - run: docker
      - run: nextflow

workflows:
  test-all:
      jobs:
        - test-bash
