version: 2.1
jobs:
  test-bash:
    docker:
      - image: conda/miniconda3
    steps:
      - checkout
      - run: conda
      - run: curl -fsSL https://get.nextflow.io | bash
      - run: nextflow
      - run: docker

workflows:
  test-all:
      jobs:
        - test-bash
